import { Request, Response } from 'express';
import { dbInstance } from './db';
import { RecurringExpense, Expense } from '../types';

export const recurringExpensesController = {
  getRecurringExpenses: (req: Request, res: Response) => {
    const userId = (req as any).user?.id || 'user_01';
    const recs = dbInstance.getRecurringExpenses().filter(r => r.userId === userId);
    res.json(recs);
  },

  createRecurringExpense: (req: Request, res: Response) => {
    const userId = (req as any).user?.id || 'user_01';
    const newRec: RecurringExpense = {
      ...req.body,
      id: `rec_${Date.now()}`,
      userId
    };
    dbInstance.saveRecurringExpense(newRec);
    res.status(201).json(newRec);
  },

  updateRecurringExpense: (req: Request, res: Response) => {
    const userId = (req as any).user?.id || 'user_01';
    const { id } = req.params;
    const recs = dbInstance.getRecurringExpenses().filter(r => r.userId === userId);
    const existing = recs.find(r => r.id === id);

    if (!existing) {
      return res.status(404).json({ error: 'Recurring expense not found' });
    }

    const updated = { ...existing, ...req.body };
    dbInstance.saveRecurringExpense(updated);
    res.json(updated);
  },

  deleteRecurringExpense: (req: Request, res: Response) => {
    const { id } = req.params;
    const success = dbInstance.deleteRecurringExpense(id);
    if (success) {
      res.json({ message: 'Deleted successfully' });
    } else {
      res.status(404).json({ error: 'Recurring expense not found' });
    }
  }
};

// Auto-generator function
export function checkAndGenerateRecurringExpenses() {
  const recurring = dbInstance.getRecurringExpenses();
  const expenses = dbInstance.getExpenses();
  
  const now = new Date();
  const todayStr = `${now.getFullYear()}-${(now.getMonth() + 1).toString().padStart(2, '0')}-${now.getDate().toString().padStart(2, '0')}`;
  
  recurring.forEach(rec => {
    // Check if an expense for this cycle has been generated recently
    // For simplicity, we just generate if today matches the start date's day of month/week.
    
    // Check if we already generated one for today
    const alreadyGenerated = expenses.find(e => 
      e.userId === rec.userId && 
      e.categoryId === rec.categoryId && 
      e.amount === rec.amount && 
      e.date === todayStr &&
      e.title.includes(rec.title)
    );

    if (alreadyGenerated) return;

    const startDate = new Date(rec.startDate);
    let shouldGenerate = false;

    if (rec.cycle === 'MONTHLY') {
      if (now.getDate() === startDate.getDate() && now >= startDate) {
        shouldGenerate = true;
      }
    } else if (rec.cycle === 'WEEKLY') {
      if (now.getDay() === startDate.getDay() && now >= startDate) {
        shouldGenerate = true;
      }
    }

    if (shouldGenerate) {
      const newExpense: Expense = {
        id: `exp_auto_${Date.now()}_${Math.floor(Math.random() * 1000)}`,
        userId: rec.userId,
        amount: rec.amount,
        categoryId: rec.categoryId,
        title: `${rec.title} (Auto)`,
        date: todayStr,
        isNecessary: true,
        isRecurring: true,
        note: `Generated by recurring cycle: ${rec.cycle}`
      };
      dbInstance.saveExpense(newExpense);
    }
  });
}
